defaults: &defaults
  docker:
      - image: circleci/node:12
  working_directory: ~/meeting-rooms

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
                - dependencies-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
                - dependencies-cache-
        - run:
            name: Install NPM packages
            command: npm i
        - save_cache:
            key: dependencies-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            paths:
                - 'node_modules'
        - persist_to_workspace:
            root: .
            paths:
                - .
  lint:
    <<: *defaults
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Run Prettier, ESLint and Stylelint
            command: npm run lint
  build:
    <<: *defaults
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Build application
            command: npm run build
        - persist_to_workspace:
            root: .
            paths:
                - dist
                - build
  test:
    <<: *defaults
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Run tests
            command: npm run test:server # npm t
  deploy:
    <<: *defaults
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Deploy to Heroku
            command: |
                git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-test-deploy:
    jobs:
        - prepare
        - lint:
            requires:
                - prepare
        - test:
            requires:
                - prepare
        - build:
            requires:
                - prepare
        - deploy:
            requires:
                - lint
                - test
                - build
            filters:
                branches:
                    only: master
