defaults: &defaults
  docker:
      - image: circleci/node:12
  working_directory: ~/meeting-rooms

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
                - dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
                - dependency-cache-
        - run:
            name: Install NPM packages
            command: npm i
        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
            paths:
                - 'node_modules'
        - persist_to_workspace:
            root: .
            paths:
                - .
  lint:
    <<: *defaults
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Run Prettier, ESLint and Stylelint
            command: npm run lint
  build:
    <<: *defaults
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Build application
            command: npm run build
        - persist_to_workspace:
            root: .
            paths:
                - dist
                - build
  test:
    <<: *defaults
    steps:
        - attach_workspace:
            at: .
        - run:
            name: Run tests # and collect coverage
            command: npm run test:server # npm t

workflows:
  version: 2
  lint-and-test:
    jobs:
        - prepare
        - lint:
            requires:
                - prepare
        - build:
            requires:
                - prepare
        - test:
            requires:
                - lint
